using System.Text;
using System.Text.Json;
using Microsoft.Extensions.Logging;

namespace Stardust.Paradox.GremlinStudio.Core.Schema;

/// <summary>
/// Implementation of schema export service for generating Stardust.Paradox interfaces.
/// </summary>
public class SchemaExportService : ISchemaExportService
{
    private readonly ILogger<SchemaExportService> _logger;

    public SchemaExportService(ILogger<SchemaExportService> logger)
    {
        _logger = logger;
    }

    public string ExportToCode(GraphSchema schema, SchemaExportOptions options)
    {
        var sb = new StringBuilder();

        // File header
        sb.AppendLine("// Auto-generated by Stardust Gremlin Studio");
        sb.AppendLine($"// Generated at: {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss} UTC");
        sb.AppendLine($"// Vertex labels: {schema.VertexLabels.Count}, Edge labels: {schema.EdgeLabels.Count}");
        sb.AppendLine();

        // Usings
        sb.AppendLine("using Stardust.Paradox.Data;");
        sb.AppendLine("using Stardust.Paradox.Data.Annotations;");
        sb.AppendLine("using Stardust.Paradox.Data.Annotations.DataTypes;");
        if (options.GenerateContext)
        {
            sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        }
        sb.AppendLine();

        // Namespace
        if (options.UseFileScopedNamespace)
        {
            sb.AppendLine($"namespace {options.Namespace};");
            sb.AppendLine();

            if (options.UseNullableReferenceTypes)
            {
                sb.AppendLine("#nullable enable");
                sb.AppendLine();
            }
        }
        else
        {
            sb.AppendLine($"namespace {options.Namespace}");
            sb.AppendLine("{");
            if (options.UseNullableReferenceTypes)
            {
                sb.AppendLine("#nullable enable");
            }
        }

        // Generate vertex interfaces
        foreach (var vertexLabel in schema.VertexLabels.OrderBy(v => v.Label))
        {
            GenerateVertexInterface(sb, vertexLabel, schema, options);
            sb.AppendLine();
        }

        // Generate typed edge interfaces
        if (options.GenerateTypedEdges)
        {
            foreach (var edgeLabel in schema.EdgeLabels.OrderBy(e => e.Label))
            {
                GenerateEdgeInterface(sb, edgeLabel, schema, options);
                sb.AppendLine();
            }
        }

        // Generate GraphContext
        if (options.GenerateContext)
        {
            GenerateGraphContext(sb, schema, options);
        }

        // Close namespace if not file-scoped
        if (!options.UseFileScopedNamespace)
        {
            sb.AppendLine("}");
        }

        return sb.ToString();
    }

    public string ExportToJson(GraphSchema schema)
    {
        var options = new JsonSerializerOptions
        {
            WriteIndented = true,
            PropertyNamingPolicy = JsonNamingPolicy.CamelCase
        };

        return JsonSerializer.Serialize(schema, options);
    }

    /// <summary>
    /// Determines if an interface needs IDynamicGraphEntity inheritance.
    /// Properties containing _ are treated as dynamic properties.
    /// </summary>
    private static bool HasDynamicProperties(IEnumerable<SchemaProperty> properties)
    {
        return properties.Any(p => IsDynamicProperty(p.Name));
    }

    /// <summary>
    /// Determines if a property should be omitted from generated interfaces.
    /// Properties containing _ are dynamic and accessed via GetProperty/SetProperty.
    /// </summary>
    private static bool IsDynamicProperty(string propertyName)
    {
        if (string.IsNullOrEmpty(propertyName))
            return false;
        return propertyName.Contains('_');
    }

    /// <summary>
    /// Gets only the regular (non-dynamic) properties that should be generated as interface members.
    /// </summary>
    private static List<SchemaProperty> GetRegularProperties(IEnumerable<SchemaProperty> properties)
    {
        return properties
            .Where(p => !IsDynamicProperty(p.Name))
            .ToList();
    }

    private void GenerateVertexInterface(StringBuilder sb, SchemaVertexLabel vertexLabel, GraphSchema schema, SchemaExportOptions options)
    {
        var regularProperties = GetRegularProperties(vertexLabel.Properties);

        // XML documentation
        if (options.IncludeXmlDocumentation)
        {
            sb.AppendLine("/// <summary>");
            sb.AppendLine($"/// Represents a '{vertexLabel.Label}' vertex in the graph.");
            sb.AppendLine($"/// Count: {vertexLabel.Count} instances");
            sb.AppendLine("/// </summary>");
        }

        // Attribute and interface declaration
        sb.AppendLine($"[VertexLabel(\"{vertexLabel.Label}\")]");
        
        // Always include IDynamicGraphEntity for flexibility with dynamic properties
        sb.AppendLine($"public interface {vertexLabel.InterfaceName} : IDynamicGraphEntity, IVertex");
        sb.AppendLine("{");

        // Id property (always present)
        if (options.IncludeXmlDocumentation)
        {
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// The unique identifier of this vertex.");
            sb.AppendLine("    /// </summary>");
        }
        sb.AppendLine("    string Id { get; }");
        sb.AppendLine();

        // Regular properties only (properties starting with _ are omitted)
        foreach (var prop in regularProperties.OrderBy(p => p.Name))
        {
            // Skip 'id' as we already generated it
            if (prop.Name.Equals("id", StringComparison.OrdinalIgnoreCase))
                continue;

            if (options.IncludeXmlDocumentation)
            {
                sb.AppendLine("    /// <summary>");
                sb.AppendLine($"    /// {GetPropertyDescription(prop, options)}");
                sb.AppendLine("    /// </summary>");
            }

            var typeName = prop.CSharpType;
            sb.AppendLine($"    {typeName} {prop.PropertyName} {{ get; set; }}");
            sb.AppendLine();
        }

        // Navigation properties
        if (options.GenerateNavigationProperties)
        {
            // Outgoing edges
            foreach (var edge in vertexLabel.OutgoingEdges.OrderBy(e => e.EdgeLabel))
            {
                var targetVertex = schema.VertexLabels.FirstOrDefault(v => v.Label == edge.VertexLabel);
                var targetInterfaceName = targetVertex?.InterfaceName ?? $"I{ToPascalCase(edge.VertexLabel)}";

                if (options.IncludeXmlDocumentation)
                {
                    sb.AppendLine("    /// <summary>");
                    sb.AppendLine($"    /// Outgoing '{edge.EdgeLabel}' edges to {edge.VertexLabel} vertices.");
                    sb.AppendLine("    /// </summary>");
                }

                sb.AppendLine($"    [EdgeLabel(\"{edge.EdgeLabel}\")]");
                var navPropertyName = GetNavigationPropertyName(edge.EdgeLabel, edge.VertexLabel, isOutgoing: true);
                if (edge.IsCollection)
                {
                    sb.AppendLine($"    IEdgeCollection<{targetInterfaceName}> {navPropertyName} {{ get; }}");
                }
                else
                {
                    sb.AppendLine($"    IEdgeReference<{targetInterfaceName}> {navPropertyName} {{ get; }}");
                }
                sb.AppendLine();
            }

            // Incoming edges (with OutLabel attribute)
            foreach (var edge in vertexLabel.IncomingEdges.OrderBy(e => e.EdgeLabel))
            {
                var sourceVertex = schema.VertexLabels.FirstOrDefault(v => v.Label == edge.VertexLabel);
                var sourceInterfaceName = sourceVertex?.InterfaceName ?? $"I{ToPascalCase(edge.VertexLabel)}";

                if (options.IncludeXmlDocumentation)
                {
                    sb.AppendLine("    /// <summary>");
                    sb.AppendLine($"    /// Incoming '{edge.EdgeLabel}' edges from {edge.VertexLabel} vertices.");
                    sb.AppendLine("    /// </summary>");
                }

                sb.AppendLine($"    [OutLabel(\"{edge.EdgeLabel}\")]");
                var navPropertyName = GetNavigationPropertyName(edge.EdgeLabel, edge.VertexLabel, isOutgoing: false);
                if (edge.IsCollection)
                {
                    sb.AppendLine($"    IEdgeCollection<{sourceInterfaceName}> {navPropertyName} {{ get; }}");
                }
                else
                {
                    sb.AppendLine($"    IEdgeReference<{sourceInterfaceName}> {navPropertyName} {{ get; }}");
                }
                sb.AppendLine();
            }
        }

        sb.AppendLine("}");
    }

    private void GenerateEdgeInterface(StringBuilder sb, SchemaEdgeLabel edgeLabel, GraphSchema schema, SchemaExportOptions options)
    {
        var regularProperties = GetRegularProperties(edgeLabel.Properties);

        // Determine source and target types
        var sourceLabel = edgeLabel.SourceLabels.FirstOrDefault() ?? "object";
        var targetLabel = edgeLabel.TargetLabels.FirstOrDefault() ?? "object";

        var sourceVertex = schema.VertexLabels.FirstOrDefault(v => v.Label == sourceLabel);
        var targetVertex = schema.VertexLabels.FirstOrDefault(v => v.Label == targetLabel);

        var sourceInterface = sourceVertex?.InterfaceName ?? $"I{ToPascalCase(sourceLabel)}";
        var targetInterface = targetVertex?.InterfaceName ?? $"I{ToPascalCase(targetLabel)}";

        // XML documentation
        if (options.IncludeXmlDocumentation)
        {
            sb.AppendLine("/// <summary>");
            sb.AppendLine($"/// Represents a '{edgeLabel.Label}' edge in the graph.");
            sb.AppendLine($"/// From: {string.Join(", ", edgeLabel.SourceLabels)} -> To: {string.Join(", ", edgeLabel.TargetLabels)}");
            sb.AppendLine($"/// Count: {edgeLabel.Count} instances");
            sb.AppendLine("/// </summary>");
        }

        // Attribute and interface declaration
        sb.AppendLine($"[EdgeLabel(\"{edgeLabel.Label}\")]");
        
        // Per the reference pattern, edges inherit IEdge<TIn, TOut>, IDynamicGraphEntity
        var baseInterfaces = $"IEdge<{sourceInterface}, {targetInterface}>, IDynamicGraphEntity";
        
        sb.AppendLine($"public interface {edgeLabel.InterfaceName} : {baseInterfaces}");
        sb.AppendLine("{");

        // Regular properties only (properties starting with _ are omitted)
        foreach (var prop in regularProperties.OrderBy(p => p.Name))
        {
            if (options.IncludeXmlDocumentation)
            {
                sb.AppendLine("    /// <summary>");
                sb.AppendLine($"    /// {GetPropertyDescription(prop, options)}");
                sb.AppendLine("    /// </summary>");
            }

            sb.AppendLine($"    {prop.CSharpType} {prop.PropertyName} {{ get; set; }}");
            sb.AppendLine();
        }

        sb.AppendLine("}");
    }

    /// <summary>
    /// Generates a clean navigation property name.
    /// </summary>
    private static string GetNavigationPropertyName(string edgeLabel, string vertexLabel, bool isOutgoing)
    {
        return ToPascalCase(edgeLabel);
    }

    private void GenerateGraphContext(StringBuilder sb, GraphSchema schema, SchemaExportOptions options)
    {
        if (options.IncludeXmlDocumentation)
        {
            sb.AppendLine("/// <summary>");
            sb.AppendLine("/// Graph context providing access to graph entities.");
            sb.AppendLine($"/// Generated from schema with {schema.VertexLabels.Count} vertex types and {schema.EdgeLabels.Count} edge types.");
            sb.AppendLine("/// </summary>");
        }

        sb.AppendLine($"public class {options.ContextClassName} : GraphContextBase");
        sb.AppendLine("{");

        // Constructor
        sb.AppendLine($"    public {options.ContextClassName}(IGremlinLanguageConnector connector, IServiceProvider serviceProvider)");
        sb.AppendLine("        : base(connector, serviceProvider)");
        sb.AppendLine("    {");
        sb.AppendLine("    }");
        sb.AppendLine();

        // GraphSet properties for each vertex type
        sb.AppendLine("    #region Vertex Sets");
        sb.AppendLine();

        foreach (var vertexLabel in schema.VertexLabels.OrderBy(v => v.Label))
        {
            var pluralName = Pluralize(ToPascalCase(vertexLabel.Label));

            if (options.IncludeXmlDocumentation)
            {
                sb.AppendLine("    /// <summary>");
                sb.AppendLine($"    /// Access to '{vertexLabel.Label}' vertices. ({vertexLabel.Count} instances)");
                sb.AppendLine("    /// </summary>");
            }

            sb.AppendLine($"    public IGraphSet<{vertexLabel.InterfaceName}> {pluralName} => GraphSet<{vertexLabel.InterfaceName}>();");
            sb.AppendLine();
        }

        sb.AppendLine("    #endregion");
        sb.AppendLine();

        // EdgeGraphSet properties for all typed edges
        if (options.GenerateTypedEdges && schema.EdgeLabels.Count > 0)
        {
            sb.AppendLine("    #region Edge Sets");
            sb.AppendLine();

            foreach (var edgeLabel in schema.EdgeLabels.OrderBy(e => e.Label))
            {
                var propertyName = ToPascalCase(edgeLabel.Label);

                if (options.IncludeXmlDocumentation)
                {
                    sb.AppendLine("    /// <summary>");
                    sb.AppendLine($"    /// Access to '{edgeLabel.Label}' edges. ({edgeLabel.Count} instances)");
                    sb.AppendLine("    /// </summary>");
                }

                sb.AppendLine($"    public IEdgeGraphSet<{edgeLabel.InterfaceName}> {propertyName} => EdgeGraphSet<{edgeLabel.InterfaceName}>(true);");
                sb.AppendLine();
            }

            sb.AppendLine("    #endregion");
            sb.AppendLine();
        }

        // InitializeModel override
        sb.AppendLine("    protected override bool InitializeModel(IGraphConfiguration configuration)");
        sb.AppendLine("    {");

        // Configure vertex collections with relationships
        var verticesWithRelationships = schema.VertexLabels
            .Where(v => v.OutgoingEdges.Count > 0 || v.IncomingEdges.Count > 0)
            .OrderBy(v => v.Label)
            .ToList();

        if (verticesWithRelationships.Count > 0)
        {
            var firstVertex = true;
            foreach (var vertexLabel in verticesWithRelationships)
            {
                if (!firstVertex)
                {
                    sb.AppendLine();
                }
                firstVertex = false;

                sb.Append($"        configuration.ConfigureCollection<{vertexLabel.InterfaceName}>()");

                foreach (var edge in vertexLabel.OutgoingEdges.OrderBy(e => e.EdgeLabel))
                {
                    var targetVertex = schema.VertexLabels.FirstOrDefault(v => v.Label == edge.VertexLabel);
                    var targetInterface = targetVertex?.InterfaceName ?? $"I{ToPascalCase(edge.VertexLabel)}";
                    var navPropertyName = GetNavigationPropertyName(edge.EdgeLabel, edge.VertexLabel, isOutgoing: true);

                    // Find corresponding incoming edge on target vertex
                    var targetIncoming = targetVertex?.IncomingEdges.FirstOrDefault(e => e.EdgeLabel == edge.EdgeLabel);

                    sb.AppendLine();
                    sb.Append($"            .Out(v => v.{navPropertyName})");

                    if (targetIncoming != null)
                    {
                        var inNavPropertyName = GetNavigationPropertyName(targetIncoming.EdgeLabel, targetIncoming.VertexLabel, isOutgoing: false);
                        sb.Append($".In<{targetInterface}>(v => v.{inNavPropertyName})");
                    }
                }

                sb.AppendLine(";");
            }

            sb.AppendLine();
        }

        // Configure edge collections
        foreach (var edgeLabel in schema.EdgeLabels.OrderBy(e => e.Label))
        {
            sb.AppendLine($"        configuration.ConfigureCollection<{edgeLabel.InterfaceName}>();");
        }

        sb.AppendLine();
        sb.AppendLine("        return true;");
        sb.AppendLine("    }");
        sb.AppendLine("}");
    }

    private string GetPropertyDescription(SchemaProperty prop, SchemaExportOptions options)
    {
        var desc = $"The {prop.Name} property.";

        if (prop.IsNullable)
            desc += " (optional)";

        if (options.IncludeSampleValuesInComments && prop.SampleValues.Count > 0)
        {
            desc += $" Samples: {string.Join(", ", prop.SampleValues.Take(3))}";
        }

        return desc;
    }

    private static string ToPascalCase(string text)
    {
        if (string.IsNullOrEmpty(text))
            return text;

        var words = text.Split(new[] { '_', '-', ' ' }, StringSplitOptions.RemoveEmptyEntries);
        return string.Concat(words.Select(w => char.ToUpperInvariant(w[0]) + w.Substring(1).ToLowerInvariant()));
    }

    private static string Pluralize(string word)
    {
        if (string.IsNullOrEmpty(word))
            return word;

        if (word.EndsWith("s", StringComparison.OrdinalIgnoreCase) ||
            word.EndsWith("x", StringComparison.OrdinalIgnoreCase) ||
            word.EndsWith("ch", StringComparison.OrdinalIgnoreCase) ||
            word.EndsWith("sh", StringComparison.OrdinalIgnoreCase))
        {
            return word + "es";
        }

        if (word.EndsWith("y", StringComparison.OrdinalIgnoreCase) &&
            word.Length > 1 &&
            !IsVowel(word[^2]))
        {
            return word[..^1] + "ies";
        }

        return word + "s";
    }

    private static bool IsVowel(char c) =>
        "aeiouAEIOU".Contains(c);
}
