<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>debug_complex_query</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="Stardust.Paradox.Data.InMemory\Stardust.Paradox.Data.InMemory.csproj" />
    <ProjectReference Include="Stardust.Paradox.Data.InMemory.Tests\Stardust.Paradox.Data.InMemory.Tests.csproj" />
  </ItemGroup>
</Project>
