<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="Stardust.Paradox.Data.InMemory\Stardust.Paradox.Data.InMemory.csproj" />
    <ProjectReference Include="Stardust.Paradox.Data.InMemory.Demo\Stardust.Paradox.Data.InMemory.Demo.csproj" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

</Project>