using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FluentAssertions;
using Stardust.Paradox.Data.InMemory;
using Stardust.Paradox.Data.InMemory.Core;
using Xunit;

namespace Stardust.Paradox.Data.InMemory.Tests
{
    /// <summary>
    /// TinkerPop Graph Structure Tests
    /// Based on: https://tinkerpop.apache.org/docs/current/dev/provider/
    /// 
    /// Tests the fundamental graph data model requirements:
    /// - Vertices and edges
    /// - Properties (single and multi-value)
    /// - Labels
    /// - Graph structure mutations
    /// </summary>
    public class TinkerPopGraphStructureTests
    {
        #region Vertex Tests

        [Fact]
        public async Task Vertex_ShouldHaveId()
        {
            var connector = InMemoryGremlinLanguageConnector.Create();
            
            await connector.ExecuteAsync("g.addV('person').property('id', 'v1')", new Dictionary<string, object>());
            
            var result = await connector.ExecuteAsync("g.V('v1').id()", new Dictionary<string, object>());
            result.Should().HaveCount(1);
            ((string)result.First()).Should().Be("v1");
        }

        [Fact]
        public async Task Vertex_ShouldHaveLabel()
        {
            var connector = InMemoryGremlinLanguageConnector.Create();
            
            await connector.ExecuteAsync("g.addV('person')", new Dictionary<string, object>());
            
            var result = await connector.ExecuteAsync("g.V().label()", new Dictionary<string, object>());
            ((string)result.First()).Should().Be("person");
        }

        [Fact]
        public async Task Vertex_ShouldSupportMultipleLabels()
        {
            // Note: TinkerPop 3.x supports multiple labels on vertices
            var connector = InMemoryGremlinLanguageConnector.Create();
            
            // Create vertex with label (multi-label is typically achieved by using :: separator or multiple hasLabel filters)
            await connector.ExecuteAsync("g.addV('person').property('id', 'v1')", new Dictionary<string, object>());
            
            var result = await connector.ExecuteAsync("g.V('v1').hasLabel('person')", new Dictionary<string, object>());
            result.Should().HaveCount(1);
        }

        [Fact]
        public async Task Vertex_ShouldSupportAutoGeneratedId()
        {
            var connector = InMemoryGremlinLanguageConnector.Create();

            await connector.ExecuteAsync("g.addV('person').property('name', 'Test')", new Dictionary<string, object>());

            var result = await connector.ExecuteAsync("g.V().hasLabel('person').id()", new Dictionary<string, object>());
            result.Should().HaveCount(1);
            ((object)result.First()).Should().NotBeNull();
        }

        [Fact]
        public async Task Vertex_WithoutEdges_ShouldBeOrphan()
        {
            var connector = InMemoryGremlinLanguageConnector.Create();
            await connector.ExecuteAsync("g.addV('person').property('id', 'isolated')", new Dictionary<string, object>());
            
            var outResult = await connector.ExecuteAsync("g.V('isolated').out()", new Dictionary<string, object>());
            var inResult = await connector.ExecuteAsync("g.V('isolated').in()", new Dictionary<string, object>());
            
            outResult.Should().BeEmpty();
            inResult.Should().BeEmpty();
        }

        [Fact]
        public async Task Vertex_Delete_ShouldAlsoDeleteEdges()
        {
            var connector = InMemoryGremlinLanguageConnector.Create();
            await connector.ExecuteAsync("g.addV('person').property('id', 'a')", new Dictionary<string, object>());
            await connector.ExecuteAsync("g.addV('person').property('id', 'b')", new Dictionary<string, object>());
            await connector.ExecuteAsync("g.V('a').addE('knows').to(g.V('b'))", new Dictionary<string, object>());
            
            // Verify edge exists
            var beforeResult = await connector.ExecuteAsync("g.E().count()", new Dictionary<string, object>());
            ((long)beforeResult.First()).Should().Be(1);
            
            // Delete vertex
            await connector.ExecuteAsync("g.V('a').drop()", new Dictionary<string, object>());
            
            // Edge should be deleted as well
            var afterResult = await connector.ExecuteAsync("g.E().count()", new Dictionary<string, object>());
            ((long)afterResult.First()).Should().Be(0);
        }

        #endregion

        #region Edge Tests

        [Fact]
        public async Task Edge_ShouldHaveId()
        {
            var connector = InMemoryGremlinLanguageConnector.Create();
            await connector.ExecuteAsync("g.addV('person').property('id', 'a')", new Dictionary<string, object>());
            await connector.ExecuteAsync("g.addV('person').property('id', 'b')", new Dictionary<string, object>());

            // Edge IDs are auto-generated in the in-memory provider; setting property('id', ...) is not supported
            await connector.ExecuteAsync("g.V('a').addE('knows').to(g.V('b'))", new Dictionary<string, object>());

            var result = await connector.ExecuteAsync("g.E().id()", new Dictionary<string, object>());
            result.Should().HaveCount(1);
            ((object)result.First()).Should().NotBeNull();
        }

        [Fact]
        public async Task Edge_ShouldHaveLabel()
        {
            var connector = InMemoryGremlinLanguageConnector.Create();
            await connector.ExecuteAsync("g.addV('person').property('id', 'a')", new Dictionary<string, object>());
            await connector.ExecuteAsync("g.addV('person').property('id', 'b')", new Dictionary<string, object>());
            await connector.ExecuteAsync("g.V('a').addE('knows').to(g.V('b'))", new Dictionary<string, object>());
            
            var result = await connector.ExecuteAsync("g.E().label()", new Dictionary<string, object>());
            ((string)result.First()).Should().Be("knows");
        }

        [Fact]
        public async Task Edge_ShouldHaveOutVertex()
        {
            var connector = InMemoryGremlinLanguageConnector.Create();
            await connector.ExecuteAsync("g.addV('person').property('id', 'a').property('name', 'Alice')", new Dictionary<string, object>());
            await connector.ExecuteAsync("g.addV('person').property('id', 'b').property('name', 'Bob')", new Dictionary<string, object>());
            await connector.ExecuteAsync("g.V('a').addE('knows').to(g.V('b'))", new Dictionary<string, object>());
            
            var result = await connector.ExecuteAsync("g.E().outV().values('name')", new Dictionary<string, object>());
            ((string)result.First()).Should().Be("Alice");
        }

        [Fact]
        public async Task Edge_ShouldHaveInVertex()
        {
            var connector = InMemoryGremlinLanguageConnector.Create();
            await connector.ExecuteAsync("g.addV('person').property('id', 'a').property('name', 'Alice')", new Dictionary<string, object>());
            await connector.ExecuteAsync("g.addV('person').property('id', 'b').property('name', 'Bob')", new Dictionary<string, object>());
            await connector.ExecuteAsync("g.V('a').addE('knows').to(g.V('b'))", new Dictionary<string, object>());
            
            var result = await connector.ExecuteAsync("g.E().inV().values('name')", new Dictionary<string, object>());
            ((string)result.First()).Should().Be("Bob");
        }

        [Fact]
        public async Task Edge_ShouldAllowSelfLoop()
        {
            var connector = InMemoryGremlinLanguageConnector.Create();
            await connector.ExecuteAsync("g.addV('person').property('id', 'a')", new Dictionary<string, object>());
            await connector.ExecuteAsync("g.V('a').addE('self').to(g.V('a'))", new Dictionary<string, object>());
            
            var outResult = await connector.ExecuteAsync("g.V('a').out('self')", new Dictionary<string, object>());
            var inResult = await connector.ExecuteAsync("g.V('a').in('self')", new Dictionary<string, object>());
            
            outResult.Should().HaveCount(1);
            inResult.Should().HaveCount(1);
        }

        [Fact]
        public async Task Edge_ShouldAllowMultipleEdgesBetweenSameVertices()
        {
            var connector = InMemoryGremlinLanguageConnector.Create();
            await connector.ExecuteAsync("g.addV('person').property('id', 'a')", new Dictionary<string, object>());
            await connector.ExecuteAsync("g.addV('person').property('id', 'b')", new Dictionary<string, object>());
            await connector.ExecuteAsync("g.V('a').addE('knows').to(g.V('b'))", new Dictionary<string, object>());
            await connector.ExecuteAsync("g.V('a').addE('likes').to(g.V('b'))", new Dictionary<string, object>());
            await connector.ExecuteAsync("g.V('a').addE('works_with').to(g.V('b'))", new Dictionary<string, object>());
            
            var result = await connector.ExecuteAsync("g.V('a').outE().count()", new Dictionary<string, object>());
            ((long)result.First()).Should().Be(3);
        }

        [Fact]
        public async Task Edge_ShouldAllowBidirectionalTraversal()
        {
            var connector = InMemoryGremlinLanguageConnector.Create();
            await connector.ExecuteAsync("g.addV('person').property('id', 'a').property('name', 'Alice')", new Dictionary<string, object>());
            await connector.ExecuteAsync("g.addV('person').property('id', 'b').property('name', 'Bob')", new Dictionary<string, object>());
            await connector.ExecuteAsync("g.V('a').addE('knows').to(g.V('b'))", new Dictionary<string, object>());
            
            // From A to B
            var forwardResult = await connector.ExecuteAsync("g.V('a').out('knows').values('name')", new Dictionary<string, object>());
            ((string)forwardResult.First()).Should().Be("Bob");
            
            // From B to A (reverse)
            var reverseResult = await connector.ExecuteAsync("g.V('b').in('knows').values('name')", new Dictionary<string, object>());
            ((string)reverseResult.First()).Should().Be("Alice");
        }

        #endregion

        #region Property Tests

        [Fact]
        public async Task VertexProperty_ShouldBeSettable()
        {
            var connector = InMemoryGremlinLanguageConnector.Create();
            await connector.ExecuteAsync("g.addV('person').property('id', 'v1').property('name', 'Test')", new Dictionary<string, object>());
            
            var result = await connector.ExecuteAsync("g.V('v1').values('name')", new Dictionary<string, object>());
            ((string)result.First()).Should().Be("Test");
        }

        [Fact]
        public async Task VertexProperty_ShouldBeUpdatable()
        {
            var connector = InMemoryGremlinLanguageConnector.Create();
            await connector.ExecuteAsync("g.addV('person').property('id', 'v1').property('name', 'Original')", new Dictionary<string, object>());
            await connector.ExecuteAsync("g.V('v1').property('name', 'Updated')", new Dictionary<string, object>());
            
            var result = await connector.ExecuteAsync("g.V('v1').values('name')", new Dictionary<string, object>());
            ((string)result.First()).Should().Be("Updated");
        }

        [Fact]
        public async Task VertexProperty_ShouldBeRemovable()
        {
            var connector = InMemoryGremlinLanguageConnector.Create();
            await connector.ExecuteAsync("g.addV('person').property('id', 'v1').property('name', 'Test').property('age', 30)", new Dictionary<string, object>());
            await connector.ExecuteAsync("g.V('v1').properties('age').drop()", new Dictionary<string, object>());
            
            var result = await connector.ExecuteAsync("g.V('v1').values('age')", new Dictionary<string, object>());
            result.Should().BeEmpty();
            
            // Name should still exist
            var nameResult = await connector.ExecuteAsync("g.V('v1').values('name')", new Dictionary<string, object>());
            nameResult.Should().HaveCount(1);
        }

        [Fact]
        public async Task EdgeProperty_ShouldBeSettable()
        {
            var connector = InMemoryGremlinLanguageConnector.Create();
            await connector.ExecuteAsync("g.addV('person').property('id', 'a')", new Dictionary<string, object>());
            await connector.ExecuteAsync("g.addV('person').property('id', 'b')", new Dictionary<string, object>());
            await connector.ExecuteAsync("g.V('a').addE('knows').to(g.V('b')).property('since', 2020)", new Dictionary<string, object>());

            var result = await connector.ExecuteAsync("g.E().values('since')", new Dictionary<string, object>());
            result.Should().HaveCount(1);
            ((int)Convert.ToInt32(result.First())).Should().Be(2020);
        }

        [Fact]
        public async Task EdgeProperty_ShouldBeUpdatable()
        {
            var connector = InMemoryGremlinLanguageConnector.Create();
            await connector.ExecuteAsync("g.addV('person').property('id', 'a')", new Dictionary<string, object>());
            await connector.ExecuteAsync("g.addV('person').property('id', 'b')", new Dictionary<string, object>());
            await connector.ExecuteAsync("g.V('a').addE('knows').to(g.V('b')).property('since', 2020)", new Dictionary<string, object>());
            await connector.ExecuteAsync("g.E().hasLabel('knows').property('since', 2021)", new Dictionary<string, object>());

            var result = await connector.ExecuteAsync("g.E().values('since')", new Dictionary<string, object>());
            result.Should().HaveCount(1);
            ((int)Convert.ToInt32(result.First())).Should().Be(2021);
        }

        [Fact]
        public async Task Property_ShouldSupportNull()
        {
            var connector = InMemoryGremlinLanguageConnector.Create();
            await connector.ExecuteAsync("g.addV('person').property('id', 'v1').property('name', 'Test')", new Dictionary<string, object>());
            
            // Setting null effectively removes the property in many implementations
            await connector.ExecuteAsync("g.V('v1').property('nullable', null)", new Dictionary<string, object>());
            
            // The vertex should still exist
            var result = await connector.ExecuteAsync("g.V('v1')", new Dictionary<string, object>());
            result.Should().HaveCount(1);
        }

        [Fact]
        public async Task Property_ShouldSupportSpecialCharacters()
        {
            var connector = InMemoryGremlinLanguageConnector.Create();
            await connector.ExecuteAsync("g.addV('person').property('id', 'v1').property('name', 'Test with spaces')", new Dictionary<string, object>());
            
            var result = await connector.ExecuteAsync("g.V('v1').values('name')", new Dictionary<string, object>());
            ((string)result.First()).Should().Be("Test with spaces");
        }

        [Fact]
        public async Task Property_ShouldSupportUnicode()
        {
            var connector = InMemoryGremlinLanguageConnector.Create();
            await connector.ExecuteAsync("g.addV('person').property('id', 'v1').property('emoji', '????')", new Dictionary<string, object>());
            
            var result = await connector.ExecuteAsync("g.V('v1').values('emoji')", new Dictionary<string, object>());
            ((string)result.First()).Should().Be("????");
        }

        #endregion

        #region Data Type Support

        [Fact]
        public async Task DataType_String_ShouldBeSupported()
        {
            var connector = InMemoryGremlinLanguageConnector.Create();
            await connector.ExecuteAsync("g.addV('test').property('id', 'v1').property('val', 'hello')", new Dictionary<string, object>());
            
            var result = await connector.ExecuteAsync("g.V('v1').values('val')", new Dictionary<string, object>());
            ((string)Convert.ToString(result.First())).Should().BeOfType<string>();
            ((string)Convert.ToString(result.First())).Should().Be("hello");
        }

        [Fact]
        public async Task DataType_Integer_ShouldBeSupported()
        {
            var connector = InMemoryGremlinLanguageConnector.Create();
            await connector.ExecuteAsync("g.addV('test').property('id', 'v1').property('val', 42)", new Dictionary<string, object>());

            var result = await connector.ExecuteAsync("g.V('v1').values('val')", new Dictionary<string, object>());
            result.Should().HaveCount(1);
            ((int)Convert.ToInt32(result.First())).Should().Be(42);
        }

        [Fact]
        public async Task DataType_Long_ShouldBeSupported()
        {
            var connector = InMemoryGremlinLanguageConnector.Create();
            await connector.ExecuteAsync("g.addV('test').property('id', 'v1').property('val', 9999999999)", new Dictionary<string, object>());

            var result = await connector.ExecuteAsync("g.V('v1').values('val')", new Dictionary<string, object>());
            result.Should().HaveCount(1);
            ((long)Convert.ToInt64(result.First())).Should().Be(9999999999L);
        }

        [Fact]
        public async Task DataType_Double_ShouldBeSupported()
        {
            var connector = InMemoryGremlinLanguageConnector.Create();
            await connector.ExecuteAsync("g.addV('test').property('id', 'v1').property('val', 3.14159)", new Dictionary<string, object>());
            
            var result = await connector.ExecuteAsync("g.V('v1').values('val')", new Dictionary<string, object>());
            ((double)Convert.ToDouble(result.First())).Should().BeApproximately(3.14159, 0.00001);
        }

        [Fact]
        public async Task DataType_Boolean_True_ShouldBeSupported()
        {
            var connector = InMemoryGremlinLanguageConnector.Create();
            await connector.ExecuteAsync("g.addV('test').property('id', 'v1').property('val', true)", new Dictionary<string, object>());
            
            var result = await connector.ExecuteAsync("g.V('v1').values('val')", new Dictionary<string, object>());
            ((bool)result.First()).Should().BeTrue();
        }

        [Fact]
        public async Task DataType_Boolean_False_ShouldBeSupported()
        {
            var connector = InMemoryGremlinLanguageConnector.Create();
            await connector.ExecuteAsync("g.addV('test').property('id', 'v1').property('val', false)", new Dictionary<string, object>());
            
            var result = await connector.ExecuteAsync("g.V('v1').values('val')", new Dictionary<string, object>());
            ((bool)result.First()).Should().BeFalse();
        }

        #endregion

        #region Graph Traversal Source Tests

        [Fact]
        public async Task GraphTraversalSource_ShouldSupportV()
        {
            var connector = InMemoryGremlinLanguageConnector.Create();
            await connector.ExecuteAsync("g.addV('test')", new Dictionary<string, object>());
            
            var result = await connector.ExecuteAsync("g.V()", new Dictionary<string, object>());
            result.Should().HaveCount(1);
        }

        [Fact]
        public async Task GraphTraversalSource_ShouldSupportE()
        {
            var connector = InMemoryGremlinLanguageConnector.Create();
            await connector.ExecuteAsync("g.addV('person').property('id', 'a')", new Dictionary<string, object>());
            await connector.ExecuteAsync("g.addV('person').property('id', 'b')", new Dictionary<string, object>());
            await connector.ExecuteAsync("g.V('a').addE('knows').to(g.V('b'))", new Dictionary<string, object>());
            
            var result = await connector.ExecuteAsync("g.E()", new Dictionary<string, object>());
            result.Should().HaveCount(1);
        }

        [Fact]
        public async Task GraphTraversalSource_ShouldSupportAddV()
        {
            var connector = InMemoryGremlinLanguageConnector.Create();
            
            var result = await connector.ExecuteAsync("g.addV('person')", new Dictionary<string, object>());
            result.Should().HaveCount(1);
        }

        [Fact]
        public async Task GraphTraversalSource_ShouldSupportAddE()
        {
            var connector = InMemoryGremlinLanguageConnector.Create();
            await connector.ExecuteAsync("g.addV('person').property('id', 'a')", new Dictionary<string, object>());
            await connector.ExecuteAsync("g.addV('person').property('id', 'b')", new Dictionary<string, object>());
            
            var result = await connector.ExecuteAsync("g.V('a').addE('knows').to(g.V('b'))", new Dictionary<string, object>());
            result.Should().HaveCount(1);
        }

        #endregion

        #region Index Support Tests

        [Fact]
        public async Task Index_LabelIndex_ShouldAccelerateQueries()
        {
            var connector = InMemoryGremlinLanguageConnector.Create();
            
            // Create vertices with different labels
            for (int i = 0; i < 100; i++)
            {
                await connector.ExecuteAsync($"g.addV('person').property('id', 'p{i}')", new Dictionary<string, object>());
            }
            for (int i = 0; i < 50; i++)
            {
                await connector.ExecuteAsync($"g.addV('company').property('id', 'c{i}')", new Dictionary<string, object>());
            }
            
            // Query by label should use index
            var result = await connector.ExecuteAsync("g.V().hasLabel('person').count()", new Dictionary<string, object>());
            ((long)result.First()).Should().Be(100);
        }

        [Fact]
        public async Task Index_PropertyIndex_ShouldAccelerateQueries()
        {
            var connector = InMemoryGremlinLanguageConnector.Create();
            
            // Create vertices with indexed property
            for (int i = 0; i < 100; i++)
            {
                await connector.ExecuteAsync($"g.addV('person').property('id', 'p{i}').property('name', 'Person{i}')", new Dictionary<string, object>());
            }
            
            // Query by property should use index if available
            var result = await connector.ExecuteAsync("g.V().has('name', 'Person50')", new Dictionary<string, object>());
            result.Should().HaveCount(1);
        }

        #endregion

        #region Cardinality Tests

        [Fact]
        public async Task Property_Cardinality_Single_ShouldReplaceValue()
        {
            var connector = InMemoryGremlinLanguageConnector.Create();
            await connector.ExecuteAsync("g.addV('person').property('id', 'v1').property('name', 'Original')", new Dictionary<string, object>());
            
            // Setting property again should replace (single cardinality is default)
            await connector.ExecuteAsync("g.V('v1').property('name', 'Updated')", new Dictionary<string, object>());
            
            var result = await connector.ExecuteAsync("g.V('v1').values('name')", new Dictionary<string, object>());
            result.Should().HaveCount(1);
            ((string)result.First()).Should().Be("Updated");
        }

        #endregion

        #region Graph Statistics

        [Fact]
        public async Task Statistics_VertexCount_ShouldBeAccurate()
        {
            var connector = InMemoryGremlinLanguageConnector.Create();
            
            for (int i = 0; i < 10; i++)
            {
                await connector.ExecuteAsync($"g.addV('node').property('id', 'n{i}')", new Dictionary<string, object>());
            }
            
            var (vertexCount, _) = connector.GetStatistics();
            vertexCount.Should().Be(10);
        }

        [Fact]
        public async Task Statistics_EdgeCount_ShouldBeAccurate()
        {
            var connector = InMemoryGremlinLanguageConnector.Create();
            
            await connector.ExecuteAsync("g.addV('a').property('id', 'a')", new Dictionary<string, object>());
            await connector.ExecuteAsync("g.addV('b').property('id', 'b')", new Dictionary<string, object>());
            
            for (int i = 0; i < 5; i++)
            {
                await connector.ExecuteAsync($"g.V('a').addE('link{i}').to(g.V('b'))", new Dictionary<string, object>());
            }
            
            var (_, edgeCount) = connector.GetStatistics();
            edgeCount.Should().Be(5);
        }

        #endregion
    }
}
